# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- '*'

pool:
  vmImage: 'ubuntu-latest'

variables:
  nodejsAppDir19: CxScan/CxScanV19
  nodejsAppDir20: CxScan/CxScanV20

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: $(nodejsAppDir19)

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: $(nodejsAppDir20)

- task: Npm@1
  inputs:
    command : 'custom'
    customCommand: 'run-script build'
    displayName: 'npm build 20'
    workingDir: $(nodejsAppDir20)

- task: Npm@1
  inputs:
    command : 'custom'
    customCommand: 'run-script build'
    displayName: 'npm build 19'
    workingDir: $(nodejsAppDir19)

- script: npm test
  displayName: Run tests
  workingDirectory: $(nodejsAppDir19)

- script: npm test
  displayName: Run tests
  workingDirectory: $(nodejsAppDir20)

- task: TfxInstaller@2
  inputs:
    version: 'v0.6.x'

- task: CmdLine@2
  inputs:
    script: 'npm install --no-optional'
  displayName: 'npm install'

- task: CmdLine@2
  inputs:
    script: 'tfx extension create --manifest-globs vss-extension.json'
  displayName: 'tfx extension create'

- task: CopyFiles@2
  inputs:
    contents: '*.vsix'
    targetFolder: $(Build.ArtifactStagingDirectory)

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    ArtifactName: 'drop'
    